title: Card Games House Rules
description: Repo for games played by mhgerov
theme: just-the-docs

url: https://mhgerov.github.io/card-games-house-rules

aux_links:
  Template Repository: https://github.com/mhgerov/card-games-house-rules
